name : Action Testing

on:
    workflow_dispatch:

jobs:

    test:

        runs-on : ubuntu-latest

        strategy:
            matrix:
                node-version : [ 20.x ]

        steps:

            -   name : Test Action
                uses : DoomCommerce/Multishop@Stable
                with :

                    Secret : ${{ secrets.Deploy }}
                    
                    Staging : Staging-A
                    Stable : main
                    
                    Commit : Sync from Stable
                    Email : User@Page.com
                    User : Username

                    Paths: |
                        'templates'
                        'snippets'
                        'sections'
                        'assets'
                        'layout/password.liquid'
                        'config/settings_schema.json'
                        ':!templates/**/*.json'
                        ':!templates/*.json'
                        ':!*/gift_card.*'
